### ISSUE TITLE
IllegalArgumentException on sending pagable information

### ISSUE THREAD

**Issue by petarkovac** [execom-eu/hawaii#1077]
Only found in server logs with exception message: java.lang.IllegalArgumentException: fromIndex(30) > toIndex(17)

**Comment by fkis1** [comment]
@jglugonja This issue can be reproduced by:
1. Navigate to administration
2. Select employees tab
3. Scroll to bottom while there are not more than 30 total employees

Expected behavior: Nothing happens
Previous behavior: App tries to load more employees resulting in a console.error

This issue should be fixed as mentioned in pull request #1092

**Comment by jglugonja** [comment]
This issue is resolved.
