### ISSUE TITLE
When trying to edit inactive User error pops up

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1120]
1.Click on Administration
2.Go to Employees tab
3.Click on Inactive users icon
4.Click on edit user 

Edit tab opens and Error pops up

**Comment by fkis1** [comment]
Unable to reproduce the issue. Can you please provide additional info?

**Comment by jglugonja** [comment]
1.Create sheduled user.
2.Leave it inactive.
3.Go to Employees tab
4.Click on Inactive users 
4.Click on edit user

After clicking on inactive(sheduled user) Error message pops up.

**Comment by fkis1** [comment]
This issue occurs due to newly created scheduled employees not having allowance. Allowance is added once an employee becomes active. Without allowance, the edit drawer for an employee cannot be populated with data, hence the error.

One solution to this issue is to add allowance to newly created scheduled employees, since inactive employees don't have access to the app, and therefore cannot make requests.
