### ISSUE TITLE
Add Stopped working at Execom date

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1125]
When deleting (archiving) an Employee should be input field for entering Stopped working at Execom date.

**Comment by EnForgac** [comment]
Logically delete method is changed.
Now it request stopped working at Execom date parameter. In case it's not sent, method was saving the date of changes.

**Comment by slobodanc93** [comment]
**Problem:** When deleting an employee, fronted currently sends a PUT request with a modified employee object in the request body. 
If the user selects a future date - when the request is received, the field 'stoppedWorkingAtExecomDate' will be updated, and later scheduled JOB will pick this up and properly delete an employee.
If the user selects today's date - then we have an issue because backend will receive an employee object that has 'stoppedWorkingAtExecomDate' filled with today's date and status 'DELETED'. JOB only picks up employees with ACTIVE status, as should be. So in this case, the employee is still part of the previous team (cleanup is not complete as we are not making use of delete service method).

**First solution:** On the backend, configure the PUT method to call the delete method if an employee with 'DELETED' status is received. This is certainly an easier solution, but we're abusing the PUT method.

**The second solution:** Frontend would make DELETE request with employee id as path variable and 'stoppedWorkingAtExecomDate' as an optional parameter. By doing this, we are moving logic to the backend. The DELETE controller would be adjusted to have a date parameter (default is today). Delete method in service would be adjusted to have different logic if the passed date is in the future (then it would update only 'stoppedWorkingAtExecomDate' and leave it for the JOB to pick it up).
