### ISSUE TITLE
Inactive Year created in Postman could not be deleted

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1216]
Steps to reproduce:
1. Send POST request in Postman (https://hawaii2.execom.eu/api/years) with following JSON in the body of request:

{
  "active": false,
  "carriedOverHoursExpirable": true,
  "carriedOverHoursExpirationDate": "2024-04-01",
  "id": 18,
  "year": 2023
}

2. Try to delete created Year.

Actual result: 
Year could not be deleted with popup error message
![Screenshot_2020-01-09 Hawaii execom](https://user-images.githubusercontent.com/58041536/74332199-854b6c80-4d95-11ea-8a2c-3ac36023665d.png)

 

P.S. You will create Year that could be deleted as expected if you send: 

{
    "id": "18",
    "year": "2023",
    "active": "false",
    "carriedOverHoursExpirable": "false",
    "carriedOverHoursExpirationDate": null
}

**Comment by slobodanc93** [comment]
These two API calls will not make an issue (order of fields is not relevant) and they will add new resources with the latest available ID.
But...POST requests can also update existing resources if we provide valid and existing ID.
If we send a request to add the year 2050 with "id": 1, it will update any value that was in a row with id 1. So later, we won't be able to delete the year 2050 because it has been used in the allowance table.
As a solution, if necessary, we could forbid updates via POST (and update only via PUT), but we would have to check it with the frontend team because they might be using POST for updating.
