### ISSUE TITLE
Security Alert - Format String Error

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1256]
A Format String error occurs when the submitted data of an input string is evaluated as a command by the application.

URL:

https://hawaii2.execom.eu/oauth2/authorize/google?redirect_uri=

**Comment by popovicbojan** [comment]
I think this is false positive. The reason format string vulnerabilities can be exploited is due to the %n operator. The %n operator will write the number of characters, which have been printed by the format string, to the memory pointed by its argument. Java produces managed code that is not susceptible to memory address overwrites as the JVM manages the process memory rather than it being the responsibility of the developer. Also, we don't use `printf()` method, so this should't be a problem.

**Comment by popovicbojan** [comment]
Review this: @stanislavgrujic

**Comment by stanislavgrujic** [comment]
I agree.
