### ISSUE TITLE
Security Alert - SQL injection may be possible

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1268]
URL:	http://localhost:8080/api/leaveprofiles?page=0&size=30+AND+1%3D1+--+

Method:	GET
Parameter:	size
Attack:	30 AND 1=1 --

The page results were successfully manipulated using the boolean conditions [30 AND 1=1 -- ] and [30 AND 1=2 -- ]
The parameter value being modified was NOT stripped from the HTML output for the purposes of the comparison
Data was returned for the original parameter.

**Comment by popovicbojan** [comment]
I think this is false positive alert. I looked at ZAPs source code to see how they check if there is SQL injection. This alert was raised because JSON responses were the same for `size=30`, `size=30 AND 1=1` and `size=30 AND 1=2`. 
We have 11 leave profiles, so when we set `size = 30` we get 11 objects. 
When `size = 30 AND 1=1` backend will try to parse it to int, because this is not possible it will fail and use default value 30 which is set on backend, so we'll get again 11 objects.
Same story with `size = 30 AND 1=2`, because it is not int we'll get 11 objects.
I think if this test was repeated with different size parameter, for example: 
`size = 5`, `size = 5 AND 1=1` and `size = 5 AND 1=2`, there would't be any alerts.

**Comment by popovicbojan** [comment]
Review this: @stanislavgrujic

**Comment by stanislavgrujic** [comment]
Could you please check if it also returns 11 records for the second example (size = 5), just to verify that it actually behaves that way?

**Comment by popovicbojan** [comment]
@stanislavgrujic 
After removing default value for size parameter Jelena repeated ZAP test and report didn't show SQL injection alert for API endpoint above.
